[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.docformatter]

[tool.black]
line-length = 80
preview = true
enable-unstable-feature = ['string_processing']
exclude = '''
/(
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.mypy_cache
  | \.vscode
  | build
  | dist
  | doc/tutorial
  | doc/_build
  | doc/auto_examples
)/
'''

[tool.isort]
profile = "black"
force_single_line = "True"
line_length = 80
extend_skip_glob=["examples/*", "guides/*"]
